/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/weapon-turret.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/weapon-turret.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['weapon-turret_1'].geometry} material={materials.colormap}>
        <mesh geometry={nodes.barrel.geometry} material={materials.colormap} position={[0, 0.23, -0.002]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/weapon-turret.glb')
